spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  devtools:
    restart:
      enabled: false

server:
  forward-headers-strategy: framework
  error:
    include-message: never
    include-stacktrace: never
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
